#!/bin/bash

# SimpleCert: https://github.com/kittrellbj/simplecert
# Automates HTTPS with Let's Encrypt and Cloudflare DNS challenge

set -e

COLOR_RED="\e[31m"
COLOR_GREEN="\e[32m"
COLOR_YELLOW="\e[33m"
COLOR_RESET="\e[0m"

print_success() { echo -e "${COLOR_GREEN}[SUCCESS]${COLOR_RESET} $1"; }
print_fail() { echo -e "${COLOR_RED}[FAIL]${COLOR_RESET} $1"; }
print_warn() { echo -e "${COLOR_YELLOW}[WARN]${COLOR_RESET} $1"; }

if [[ $EUID -ne 0 ]]; then print_fail "Run as root (sudo)"; exit 1; fi
print_success "Running as root"

# Ask for one or more domains
echo "Enter one or more fully-qualified domain names (FQDNs) separated by spaces:"
echo "(e.g., host1.domain.tld host2.domain.tld)"
read -p "Domain(s): " CERT_DOMAINS
if [[ -z "$CERT_DOMAINS" ]]; then
    print_fail "No domain(s) provided"
    exit 1
fi

# Ask for the user's email address
read -p "Enter your email address for Let's Encrypt registration and expiry notices: " CERT_EMAIL
if [[ -z "$CERT_EMAIL" ]]; then
    print_fail "No email address provided"
    exit 1
fi

FIRST_DOMAIN=$(echo "$CERT_DOMAINS" | awk '{print $1}')
if [[ ! "$FIRST_DOMAIN" =~ ^[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$ ]]; then
    print_warn "First domain doesn't look valid. Proceeding anyway..."
fi

CRED_PATH="/etc/letsencrypt/cloudflare.ini"
CERTBOT_LOG="/var/log/certbot_simplecert.log"
NGINX_SNIPPET="/etc/letsencrypt/simplecert_nginx_snippet.conf"

# Install Certbot and plugin
apt-get update -y && apt-get install -y software-properties-common
add-apt-repository universe -y
apt-get update -y
if apt-get install -y certbot python3-certbot-dns-cloudflare; then
  print_success "Certbot and DNS plugin installed"
else
  print_fail "Certbot install failed"; exit 1
fi

# Prompt for API token
if [ ! -f "$CRED_PATH" ]; then
  read -p "Enter your Cloudflare API token: " TOKEN
  echo "dns_cloudflare_api_token = $TOKEN" > "$CRED_PATH"
  chmod 600 "$CRED_PATH"
  print_success "Cloudflare token saved"
else
  print_warn "Using existing Cloudflare credentials"
fi

# Request certificate
if certbot certonly --dns-cloudflare --dns-cloudflare-credentials "$CRED_PATH"         --non-interactive --agree-tos --email "$CERT_EMAIL"         $(for d in $CERT_DOMAINS; do echo -n "-d $d "; done)         > "$CERTBOT_LOG" 2>&1; then
  print_success "Certificate acquired for $CERT_DOMAINS"
else
  print_fail "Certificate request failed. See $CERTBOT_LOG for details"
  exit 1
fi

echo
print_success "Use this in your Nginx config for each domain:"
echo "  (You can include this file in each server block)"
echo "  include $NGINX_SNIPPET;"

echo "# Generated by SimpleCert" > "$NGINX_SNIPPET"
for DOMAIN in $CERT_DOMAINS; do
  echo "" >> "$NGINX_SNIPPET"
  echo "# For $DOMAIN" >> "$NGINX_SNIPPET"
  echo "ssl_certificate /etc/letsencrypt/live/$DOMAIN/fullchain.pem;" >> "$NGINX_SNIPPET"
  echo "ssl_certificate_key /etc/letsencrypt/live/$DOMAIN/privkey.pem;" >> "$NGINX_SNIPPET"
done

print_success "Nginx config snippet saved to $NGINX_SNIPPET"
print_success "You can now configure Nginx to use the certificates"